### PR TITLE
Booleans were not handled when generating UGen code.

### PR DESCRIPTION
**Pull request by abramhindle**
We need gulp to make this build so I added that in the README.

### CODE REVIEW

**Comment by abramhindle** [comment]
Also I think you use a Mac or Windows because there was a case sensitivity build problem. Also big.js wasn't part of the dependencies.

Now I've got it built on ubuntu 16.04 just fine, but I had to get a node 6 deb package.

**Comment by abramhindle** [comment]
There was no Clamp. And Pow was wrong. Booleans were not handled so the Sampler example did not work. It would blow up when true was used for the loops attribute. There's a slight mess in that I pointed it my genish repo. I suggest that you pull this branch and build yourself since that messy dist stuff is included as well. Probably should not commit dist files :-/

**Comment by charlieroberts** [comment]
This branch still had the readme from the previous branches, which was pretty much obsolete. Most of the info is wrong. I'll try and update it (including your changes); obviously that's important if people are going to start using it!

I wonder if I should do some type of hack to convert booleans to ints automatically.... hmmm.

Anyways, let me work through these!

**Comment by charlieroberts** [comment]
Nice, as I just ran into bugs with the mono bus...

**Pull request merged**
